import "./cascade-evidence.css";

/** Primary-source context for the model; these results do not validate UTP. */
export function mountCascadeEvidence(element: HTMLElement) {
  element.innerHTML = `
    <section class="cascade-evidence" aria-labelledby="evidence-heading">
      <div class="cascade-answer"><p class="eyebrow">WHAT THE EVIDENCE SAYS</p><h2 id="evidence-heading">Some jams can be prevented.<br>Some queues have to exist.</h2><p>A driver brakes. The next driver brakes harder. Farther back, cars stop. That kind of wave can be dampened. A full exit is different: until cars can leave it, the cars behind it have to wait.</p></div>
      <div class="cascade-findings">
        <article><span class="cascade-ref">01 / STOP-AND-GO WAVES</span><h3>One car can help the cars behind it.</h3><p>In a 22-car circular-track experiment, researchers used one controlled vehicle to dampen waves produced by human drivers. That demonstrates the mechanism in a controlled setting; it doesn’t establish how much congestion a whole city could avoid.</p><a href="https://arxiv.org/abs/1705.01693" target="_blank" rel="noreferrer">Read the field experiment ↗</a></article>
        <article><span class="cascade-ref">02 / RAMPS AND FREEWAYS</span><h3>A short wait can prevent a much longer one.</h3><p>When Minnesota switched off its ramp meters for a regional evaluation, freeway travel times increased by 22%. Metering helps regulate entry, but ramp waits and queues on city streets still matter.</p><a href="https://ops.fhwa.dot.gov/bn/resources/case_studies/minnstp_mn.htm" target="_blank" rel="noreferrer">Read the FHWA case study ↗</a></article>
        <article><span class="cascade-ref">03 / THE CONTROLLER MATTERS</span><h3>Connected doesn’t automatically mean smoother.</h3><p>Researchers found that seven tested 2018-model cruise control systems could amplify slowdowns. A platoon test confirmed the effect for one model. Vehicles need a policy that dampens waves; exchanging messages alone doesn’t provide one.</p><a href="https://arxiv.org/abs/1905.02108" target="_blank" rel="noreferrer">Read the stability study ↗</a></article>
      </div>
      <div class="capacity-proof"><div><span class="cascade-ref">A LIMIT WE CAN PROVE</span><h3>If an exit can serve at most 3,000 cars an hour…</h3><p>Suppose that is its physical maximum even with the best coordinated control, and 3,600 cars need it each hour. At least 600 extra cars accumulate. Autonomy can raise usable capacity, but demand above the improved maximum still creates a queue.</p></div><div class="capacity-arithmetic" aria-label="3,600 arrivals minus at most 3,000 departures equals at least 600 unfinished trips per hour"><span>3,600 <small>arriving / hour</small></span><span>− 3,000 <small>maximum leaving / hour</small></span><strong>≥ 600 <small>extra unfinished trips / hour</small></strong></div></div>
      <div class="cascade-conclusion"><p><strong>This has reached an actual interstate.</strong> The CIRCLES team tested 100 vehicles from different manufacturers on I-24, using a shared speed planner and local vehicle controllers. Their report describes wave damping, while also recording waves that remained. <a class="inline-evidence-link" href="https://arxiv.org/html/2402.17043v1#S24" target="_blank" rel="noreferrer">Read the open-road study</a>.</p><p><strong>The useful version of the theory:</strong> early information and the right controllers can keep some disturbances from growing into larger jams, especially while demand is still within capacity. The question is how much, under which conditions, and who bears the remaining wait.</p><p>The new city model tests queues filling roads and blocking their neighbors. The individual braking waves above require a different model and road experiments. Neither model is a real-city forecast.</p><a href="https://github.com/ben4mn/universal-traffic-protocol/blob/main/docs/cascades.md" target="_blank" rel="noreferrer">Read the argument, sources, and tests ↗</a></div>
    </section>`;
}
